# Generated by Django 5.2.13 on 2026-04-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('opinion', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'Yomon'), (2, 'O‘rtacha'), (3, 'Yaxshi'), (4, 'Zo‘r'), (5, 'A’lo')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
